# RAG System Configuration

# Data paths
data_directory: "data"
vector_db_directory: "vector_db"

# Embedding model settings
embedding_model:
  type: "huggingface"  # Use HuggingFace for vector store compatibility
  name: "sentence-transformers/all-mpnet-base-v2"  # 768-dim embeddings
  kwargs:
    device: "cpu"

# Text splitter settings
text_splitter:
  chunk_size: 1000
  chunk_overlap: 200

# Retrieval settings
retrieval:
  top_k: 5

# LLM settings - using Azure AI Inference exclusively
llm:
  type: "azure_inference"
  endpoint: "https://models.inference.ai.azure.com"  # Will use env var if this is empty
  model_name: "gpt-4o"  # Will use env var if this is empty
  temperature: 0.7
  max_tokens: 1000
  top_p: 1.0
  system_message: "You are a helpful assistant that provides accurate, factual information based on the provided context."

# Chat settings
max_chat_history: 10
