data_directory: data
embedding_model:
  endpoint: https://models.inference.ai.azure.com
  kwargs:
    device: cpu
  model_name: text-embedding-3-small
  type: azure_inference
file_processors:
  csv:
    processor: structured
    separator: ','
  docx:
    processor: auto_detect
    text_splitter:
      chunk_overlap: 150
      chunk_size: 800
  md:
    processor: auto_detect
    text_splitter:
      chunk_overlap: 100
      chunk_size: 500
  pdf:
    processor: auto_detect
    text_splitter:
      chunk_overlap: 200
      chunk_size: 1000
  txt:
    processor: auto_detect
    text_splitter:
      chunk_overlap: 250
      chunk_size: 1200
llm:
  endpoint: https://models.inference.ai.azure.com
  max_tokens: 1000
  model_name: gpt-4o
  system_message: You are a helpful assistant that provides accurate, factual information
    based on the provided context.
  temperature: 0.7
  top_p: 1.0
  type: azure_inference
max_chat_history: 10
parallel_processing:
  enabled: true
  max_workers: 4
retrieval:
  top_k: 5
text_splitter:
  chunk_overlap: 200
  chunk_size: 1000
vector_db_directory: vector_db_1742166892
